name: langgraph
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.17
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - pyzmq=26.2.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - filetype==1.2.0
      - google-ai-generativelanguage==0.6.18
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.4
      - grpcio==1.74.0
      - grpcio-status==1.74.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.27
      - langchain-core==0.3.75
      - langchain-google-genai==2.1.10
      - langchain-text-splitters==0.3.11
      - langgraph==0.6.6
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.6.4
      - langgraph-sdk==0.2.6
      - langsmith==0.4.25
      - orjson==3.11.3
      - ormsgpack==1.10.0
      - proto-plus==1.26.1
      - protobuf==6.32.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dotenv==1.1.1
      - pyyaml==6.0.2
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - tenacity==9.1.2
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - xxhash==3.5.0
      - zstandard==0.24.0
